x-common-deploy: &common-deploy
  restart_policy:
    condition: on-failure
    delay: 5s
    window: 120s
x-common-env: &common-env
  PGID: 1000
  PUID: 1000
  TZ: Europe/Paris

networks:
  backend: {}
  public:
    external: true

services:
  duplicati:
    cap_add:
      - SETUID
      - SETGID
    cap_drop:
      - "ALL"
    command:
      - duplicati-server
      - --webservice-interface=any
      - --webservice-allowed-hostnames=*
      - --tempdir=/tmp
    deploy:
      !!merge <<: *common-deploy
      labels:
        # Allow traefik to process this container
        - "traefik.enable=true"
        - "traefik.http.routers.duplicati.rule=Host(`duplicati.$DOMAIN_NAME`)"
        - "traefik.http.routers.duplicati.entrypoints=https"
        - "traefik.http.services.duplicati.loadbalancer.server.port=8200"
        - "traefik.http.routers.duplicati.middlewares=auth-admin"
    environment:
      !!merge <<: *common-env
      SETTINGS_ENCRYPTION_KEY: $DUPLICATI_ENCRYPTION_KEY
      DUPLICATI__WEBSERVICE_PASSWORD: $SUDO_PASSWORD
    image: lscr.io/linuxserver/duplicati:latest@sha256:d956e71be2ec9788ab617b8baf6e7e6ed7e3a98362df40440f9ce8113b58cbdd
    networks:
      - public
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - $STORAGE_PATH/core/duplicati/config:/config
      - $STORAGE_PATH:/docker
      - $BACKUP_PATH:/backups
    tmpfs:
      - /defaults:rw,uid=1000,gid=1000
      - /tmp:rw,uid=1000,gid=1000