x-common-deploy: &common-deploy
  restart_policy:
    condition: on-failure
    delay: 5s
    window: 120s
x-common-env: &common-env
  PGID: 1000
  PUID: 1000
  TZ: Europe/Paris

networks:
  backend: {}
  public:
    external: true

services:
  keycloak:
    cap_drop:
      - "ALL"
    command: ["start-dev", "--http-port", "8080"]
    deploy:
      !!merge <<: *common-deploy
      labels:
        # Allow traefik to process this container
        - "traefik.enable=true"
        - "traefik.swarm.network=public"
        - "traefik.http.routers.keycloak.rule=Host(`auth.$DOMAIN_NAME`)"
        - "traefik.http.routers.keycloak.entrypoints=https"
        - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
    environment:
      !!merge <<: *common-env
      KC_DB: postgres
      KC_DB_PASSWORD: keycloak
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_HOST: keycloak_database
      KC_DB_USERNAME: keycloak
      KC_BOOTSTRAP_ADMIN_USERNAME: administrator
      KC_BOOTSTRAP_ADMIN_PASSWORD: $SUDO_PASSWORD
      KC_HEALTH_ENABLED: "true"
      KC_HTTP_MANAGEMENT_PORT: "9081"
      KC_HOSTNAME: https://auth.$DOMAIN_NAME
      KC_PROXY: edge
      KC_FEATURES: docker
    image: quay.io/keycloak/keycloak:26.4.6@sha256:d0d4037f17521a7f06137afd5a0eecb1f977f4ade773ae7755f1ee82cad8a576
    networks:
      - public
      - backend
    security_opt:
      - no-new-privileges:true
    user: "1000:1000"
    volumes:
      - $STORAGE_PATH/core/keycloak/data:/opt/keycloak/data
  
  keycloak_database:
    deploy:
      !!merge <<: *common-deploy
    environment:
      !!merge <<: *common-env
      POSTGRES_DB: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_USER: keycloak
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test: ["CMD-SHELL", "pg_isready -d keycloak -U keycloak"]
      timeout: 5s
    image: postgres:18.1@sha256:5ec39c188013123927f30a006987c6b0e20f3ef2b54b140dfa96dac6844d883f
    networks:
      - backend
    tmpfs:
      - /var/run/postgresql:rw,uid=1000,gid=1000
    user: "1000:1000"
    volumes:
      - $STORAGE_PATH/core/keycloak/database:/var/lib/postgresql