x-common-deploy: &common-deploy
  restart_policy:
    condition: on-failure
    delay: 5s
    window: 120s
x-common-env: &common-env
  PGID: 1000
  PUID: 1000
  TZ: Europe/Paris

networks:
  backend: {}
  public:
    external: true

services:
  whoami:
    cap_drop:
      - "ALL"
    deploy:
      !!merge <<: *common-deploy
      labels:
        # Allow sablier to process this container
        - "sablier.enable=true"
        - "sablier.group=whoami"
        # Homepage 
        - "homepage.group=Web Services"
        - "homepage.name=whoami"
        - "homepage.icon=whoami.png"
        - "homepage.href=https://whoami.$DOMAIN_NAME"
        - "homepage.description=Request echo service used to verify reverse-proxy, headers, and auth middleware"
        # Allow traefik to process this container
        - "traefik.enable=true"
        - "traefik.swarm.lbswarm=true"
        - "traefik.http.routers.whoami.rule=Host(`whoami.$DOMAIN_NAME`)"
        - "traefik.http.routers.whoami.entrypoints=https"
        - "traefik.http.routers.whoami.middlewares=sablier-whoami@swarm"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
        - "traefik.http.middlewares.sablier-whoami.plugin.sablier.group=whoami"
        - "traefik.http.middlewares.sablier-whoami.plugin.sablier.dynamic.displayName=Whoami"
        - "traefik.http.middlewares.sablier-whoami.plugin.sablier.sessionDuration=15s"
    environment:
      !!merge <<: *common-env
    image: traefik/whoami:v1.11@sha256:200689790a0a0ea48ca45992e0450bc26ccab5307375b41c84dfc4f2475937ab
    networks:
      - public
    security_opt:
      - no-new-privileges:true
    user: "1000:1000"